system:
    default:
        location_view:
            block_item:
                product:
                    template: "eZDemoBundle:block_item:product.html.twig"
                    match:
                        Identifier\ContentType: "product"
