system:
    default:
        location_view:
            block_item:
                product:
                    template: "eZSyliusBundle:block_item:product.html.twig"
                    match:
                        Identifier\ContentType: "product"
            full:
                product:
                    template: "eZSyliusBundle:product:product.html.twig"
                    match:
                        Identifier\ContentType: "product"